name: Spring Boot CI/CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: maven

      - name: Build App
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t vishnukanthmca/springboot-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to DockerHub
        run: docker push vishnukanthmca/springboot-app:latest

      - name: Set app image URI for Terraform
        run: echo "APP_IMAGE_URI=vishnukanthmca/springboot-app:latest" >> $GITHUB_ENV
